targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/{{file}}.dart': 'lib/generated/source_gen/{{file}}.g.dart'
      freezed:
        options:
          build_extensions:
            '^lib/{{file}}.dart': 'lib/generated/freezed/{{file}}.freezed.dart'